### ISSUE TITLE
a command to kick the bot from voice chat channels

### ISSUE THREAD

**Issue by mitski-shinm** [q31r/EthelMC#4]
The bot is currently stuck in the voice chat channels after using !joinvc1. Could you please add a command that allows us to kick it from the voice chat channels?
Thanks a lot, your efforts are truly appreciated for our community 💓
- NeoMC

**Comment by Qmirdev** [comment]
Absolutely! I just implemented a new feature in the bot that allows it to smoothly exit a voice chat channel whenever it is currently engaged in one.
```python
# Usage: !leavevc
@client.command()
async def leavevc(ctx):
  if str(ctx.message.author.id) in OWNER_UID:
    if ctx.voice_client:
      await ctx.voice_client.disconnect()
      await ctx.send("Left the voice channel")
    else:
      await ctx.send("Not in a voice channel")
  else:
    await ctx.send('You are not authorized to use this command.')
```
np at all <3
